### ISSUE TITLE
Does not support proxies (HTTP_PROXY)

### ISSUE THREAD

**Issue by croensch** [phar-io/composer-distributor#22]
Probably because the HTTP client is very much native. But if i'm not mistaken a stream-context could be created.

**Comment by heiglandreas** [comment]
I'll take a look at it. What would be your reasoning for using a proxy in this scenario? Debugging?

**Comment by croensch** [comment]
I was installing `phpdocumentor/shim`, which makes use of this plugin, in a docker container on a ci system that only has internet access via proxy.

**Comment by heiglandreas** [comment]
I'll see to a fast fix for that!

**Comment by sebastianfeldmann** [comment]
This was fixed in version 1.0.1
