### ISSUE TITLE
Deprecation Notice fixed in main but not in tag 1.0.1

### ISSUE THREAD

**Issue by Mariusrfx** [phar-io/composer-distributor#25]
Hello, 
When I execute composer update I get 5 deprecation warnings, this is one of them (Deprecation Notice: Return type of PharIo\ComposerDistributor\FileList::current() should either be compatible with Iterator), and i saw that you already fixed it in [Fix deprecation notice on PHP 8.1](https://github.com/phar-io/composer-distributor/commit/ec99128d640e2ebef442e166f89015d0780bc0c8)
but you didn't pushed a new tag, can you please push a new tag to fix this warnings?
Thank you

**Comment by sebastianfeldmann** [comment]
Fixed in version 1.0.2 sorry for it taking so long
