### ISSUE TITLE
Create Packagist package

### ISSUE THREAD

**Issue by sebastianfeldmann** [phar-io/composer-distributor#3]
We have to create a Packagist package `phar-io/composer-distributor` so we can actually install it and play around with the current state to see how it works in action ;)

**Comment by theseer** [comment]
> phar-io/composer-distributor has been added to the package list, the repository will now be crawled.

**Comment by theseer** [comment]
The registration is apparently completed.

I added @sebastianfeldmann and @heiglandreas as co-maintainer.

~~@sebastianfeldmann: Not sure if your account on packagist is @sebastianfeldmann, the avatar is a fractal ;)~~ Seems like it. At least the other projects listed fit ;)

**Comment by heiglandreas** [comment]
Don't we also need a `phar-io/mediator` package? Otherwise people can't run `composer create-project phar-io/mediator`...

**Comment by theseer** [comment]
Wrong project ;)
