### ISSUE TITLE
Verification implementation

### ISSUE THREAD

**Issue by sebastianfeldmann** [phar-io/composer-distributor#6]
Currently `GnuPg` is used to handle the verification.
`phive` uses `phar-io/gnu-pg`. Should we use this as well?

**Comment by heiglandreas** [comment]
Internally PharIo/GnuPG is used. But it is a wrapper around GnuPG which is why that crops up...

**Comment by sebastianfeldmann** [comment]
This means the import is currently wrong? Because it imports some global `\GnuPG` class

https://github.com/phar-io/composer-distributor/blob/6523d40f5ccb38f5a5b58b18a51d355d4f7b4e72/src/Service/Verify.php#L12-L25

phpstan sais `unknown class`

**Comment by heiglandreas** [comment]
Yes and no.... 

In [phar-io/gnupg](https://github.com/phar-io/gnupg/blob/master/src/Factory.php#L39-L41) a class alias is created if `\GnuPG` does not exist. So the import should work out without issue.

**Comment by heiglandreas** [comment]
That was also the reason why I didn't require `ext-gpg` in the `composer.json`

**Comment by sebastianfeldmann** [comment]
Got it 👍
